"""test

Revision ID: 357ab64c0cdb
Revises: acb0d0453bdb
Create Date: 2023-05-07 16:08:35.788489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '357ab64c0cdb'
down_revision = 'acb0d0453bdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_buyer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('account_seller', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('account_verification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('telegram.buyer_message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('telegram.buyer_message', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('account_verification', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('account_seller', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('account_buyer', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
