"""update buyer

Revision ID: 4d785a64914f
Revises: d439b342d45d
Create Date: 2023-05-12 21:40:37.714036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d785a64914f'
down_revision = 'd439b342d45d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_buyer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paypal', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('amazon_url', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('amazon_screenshot', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_buyer', schema=None) as batch_op:
        batch_op.drop_column('amazon_screenshot')
        batch_op.drop_column('amazon_url')
        batch_op.drop_column('paypal')

    # ### end Alembic commands ###
