"""Add check constraints to Seller table_2

Revision ID: 5546805b9425
Revises: cdbe271323aa
Create Date: 2023-10-26 23:52:00.371948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5546805b9425'
down_revision = 'cdbe271323aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_seller', schema=None) as batch_op:
        batch_op.add_column(sa.Column('performance_score', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_seller', schema=None) as batch_op:
        batch_op.drop_column('performance_score')

    # ### end Alembic commands ###
