"""order review_Screenshit


Revision ID: 6368f20b35f7
Revises: 
Create Date: 2023-11-05 23:25:35.690161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6368f20b35f7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('review_screenshot', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('review_screenshot')

    # ### end Alembic commands ###
