"""order_id to ordeR_number

Revision ID: 8f9a3430b284
Revises: 1212312312312
Create Date: 2023-11-06 21:05:17.595549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f9a3430b284'
down_revision = '1212312312312'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_number', sa.Integer(), nullable=True))
        batch_op.drop_constraint('order_order_id_key', type_='unique')
        batch_op.create_unique_constraint(None, ['order_number'])
        batch_op.drop_column('order_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('order_order_id_key', ['order_id'])
        batch_op.drop_column('order_number')

    # ### end Alembic commands ###
