"""Add check constraints to Seller table

Revision ID: cdbe271323aa
Revises: sdfdsfdsfsdfs
Create Date: 2023-10-26 23:51:42.280427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdbe271323aa'
down_revision = 'sdfdsfdsfsdfs'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_seller', schema=None) as batch_op:
        batch_op.drop_column('performance_score')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_seller', schema=None) as batch_op:
        batch_op.add_column(sa.Column('performance_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
