"""product update and order tab;e

Revision ID: ef1e65011d8c
Revises: d6b4f2845335
Create Date: 2023-05-27 15:05:45.449684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ef1e65011d8c"
down_revision = "d6b4f2845335"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("product", schema=None) as batch_op:
        batch_op.add_column(sa.Column("count", sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("product", schema=None) as batch_op:
        batch_op.drop_column("count")

    # ### end Alembic commands ###
