from enum import Enum

class ProductStatus(Enum):
    AVAILABLE = 'AVAILABLE'
    SOLD_OUT = 'SOLD_OUT'
    DISCONTINUED = 'DISCONTINUED'

class Platform(Enum):
    AMAZON = 'AMAZON'

class Country(Enum):
    GERMANY = 'GERMANY'
    USA = 'USA'
   
class ServiceType(Enum):
    REVIEW = 'REVIEW'
    FEEDBACK = 'FEEDBACK'

class OrderStatus(Enum):
    WAITING_CONFIRMATION = "WAITING_CONFIRMATION"
    CONFIRMED = "CONFIRMED"
    SS_SENT = "SS_SENT"
    WAITING_SS = "WAITING_SS"
    SS_ACCEPTED = "SS_ACCEPTED"
    SS_REJECTED = "SS_REJECTED"
    ORDERED = "ORDERED"
    REJECTED = "ORDER_REJECTED"
    DETAILS_SUBMITTED = "DETAILS_SUBMITTED"
    REVIEW_SUBMITTED = "REVIEW_SUBMITTED"
    PAYPAL_REFUNDED = "PAYPAL_REFUNDED"
    COMPLETED = "COMPLETED"